### ISSUE TITLE
Question about design

### ISSUE THREAD

**Issue by danjessen** [ikcoin/IkCase#1]
Love the case ... Do you have a version without split backspace?

**Comment by bernatmarcilla** [comment]
Nope, there is not a current version with no split backspace, but that is a good suggestion, let me take a look! 😉

**Comment by danjessen** [comment]
Sounds good

**Comment by bernatmarcilla** [comment]
Hi @danjessen, I have created the #feat-2uBackspace branch with the 2u backspace DWG and DXF plate files. c13bdf9b814c7c89e16b2abe7d79a4267404473c commit. I will update the README.
